name: dev_toolkit
description: "A versatile Flutter library offering a collection of extension methods, helper classes, and reusable utility functions designed to streamline development and boost productivity across multiple projects. With dev_toolkit, simplify your code and build faster, more maintainable applications."
version: 0.0.7
homepage: https://github.com/salihagic/dev_toolkit

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  crypto: ^3.0.6
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.4.0
  device_calendar: ^4.3.3
  permission_handler: ^12.0.0+1
  haptic_feedback: ^0.5.1+1
  easy_debounce: ^2.0.3
  flutter_udid: ^4.0.0
  go_router: ^15.1.1
  open_file: ^3.5.10
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0

flutter:

import_sorter:
  emojis: false 
  comments: false 